version: '3'

services:
  grokmirror:
    build:
      # uses the parent as context to install both grokmirror and public-inbox from source
      context: ..
      dockerfile: ./grokmirror/Containerfile

    environment:
      - HOME=/tmp

    # stdin_open: true
    user: "${UID}:${GID}"
    volumes:
    - ./lore.conf:/config/lore.conf:z
    - ../public-inbox/pi-configs/:/etc/public-inbox/:z
    - ../data/:/data:z
    command: grok-pull -v -c /config/lore.conf

