FROM docker.io/library/python:3.14-slim-trixie as base

ARG USER_ID=1000
ARG GROUP_ID=1000

USER root

RUN export DEBIAN_FRONTEND=noninteractive &&\
	apt-get update && \
	apt-get install -y \
	git \
	perl \
	sqlite3 \
	curl \
	make \
	build-essential \
	# xapian search
	xapian-omega \
	libsearch-xapian-perl \
	# public-inbox \
	libplack-perl \
	libinline-c-perl

WORKDIR /grokmirror

# install grokmirror from source
COPY ./grokmirror/grokmirror-source .
RUN pip install --upgrade pip && \
	pip install .

# install public-inbox from source
WORKDIR /app

WORKDIR /public-inbox

COPY ./public-inbox/public-inbox-source/ .

RUN yes | ./install/deps.perl all

RUN perl Makefile.PL && \
	make && \
	make install

WORKDIR /data
