user  angie;
worker_processes  auto;

error_log  /var/log/angie/error.log notice;
pid        /var/run/angie.pid;

events {
    worker_connections 1024;
}

http {
  proxy_cache_path /tmp/angie_cache levels=1:2 keys_zone=local_cache:30m max_size=510m inactive=10d; 
  proxy_temp_path /tmp/angie_proxy 1 2;

  # API
  server{
   listen 80;
   listen 443;
   listen 119;
	 

   server_tokens off;

   # correctly load css
   include /etc/angie/mime.types;

	 # listen
   
	 /static/theme.css 

  }
}

